Mathias Score.java eingefügt. Test läuft allerdings auf komische Exception: java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing 	at java.lang.ClassLoader.defineClass1(Native Method) 	at java.lang.ClassLoader.defineClassCond(Unknown Source) 	at java.lang.ClassLoader.defineClass(Unknown Source) 	at java.security.SecureClassLoader.defineClass(Unknown Source) 	at java.net.URLClassLoader.defineClass(Unknown Source) 	at java.net.URLClassLoader.access$000(Unknown Source) 	at java.net.URLClassLoader$1.run(Unknown Source) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(Unknown Source) 	at java.lang.ClassLoader.loadClass(Unknown Source) 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) 	at java.lang.ClassLoader.loadClass(Unknown Source) 	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:13) 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57) 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29) 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57) 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197) Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing 	at java.net.URLClassLoader$1.run(Unknown Source) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(Unknown Source) 	at java.lang.ClassLoader.loadClass(Unknown Source) 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) 	at java.lang.ClassLoader.loadClass(Unknown Source) 	... 25 more